### ISSUE TITLE
Add Metrics around requests to KCP API Server

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#108]
**What**

Look at using https://github.com/linki/instrumented_http to allow us to monitor requests to the KCP api server

**Comment by david-martin** [comment]
@maleck13 @jjaferson I stumbled on this topic while looking at metrics for the glbc dashboard panels.
In another operater we were able to get a bunch of metrics from the client-go rest client.
However, since the informer pattern is being used rather than rest, I tried to find if there's a way to enable informer metrics.

I came across this issue https://github.com/linkerd/linkerd2/issues/6354,
which linked to this PR https://github.com/linkerd/linkerd2/pull/6447
It might provide a jump off point.
However I wonder if the use of the informer pattern means that you wouldn't view requests to the KCP API server in a traditional http request way?
What would you see the goal or use cases of a dashboard being? Answering this should help focus on what to show.

**Comment by david-martin** [comment]
There's a reflector metrics interface exposed in https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector_metrics.go where you can set a metrics provider (e.g prometheus) that may give some useful informer metrics. 
My understanding is that it's the reflector component that actually lists and watches resources (taken from https://medium.com/geekculture/advanced-kubernetes-operator-development-with-finalizer-informer-and-webhook-2339e9fd8eba)
I'm unsure of where/how updates to resources are handled (though that's likely outside the informer)
