### ISSUE TITLE
Investigate using the location APIs in KCP

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#118]
**What**

0.4.0 of KCP is available. It introduces the location APIs. We should take a look at them , try them and see how / if they impact on our controller.

We should set up a location with multiple clusters, then attempt to assign a namespace to a location and observe the behaviour. We should then look to see is it possible to have an application deployed across multiple clusters in a location. (reach out to KCP team on this)

Requires https://github.com/Kuadrant/kcp-glbc/issues/197

**Comment by maleck13** [comment]
Ideally would like to understand how we advertise a set of clusters that have Gateway API installed as part of a location

**Comment by maleck13** [comment]
https://github.com/kcp-dev/kcp/pull/942

**Comment by mikenairn** [comment]
The location/placement API in kcp are still being actively developed and are not available by default in 0.4.0. It looks as if they will be available in the next kcp release (0.5.0). Details of the testing done so far can be found here https://github.com/Kuadrant/kcp-glbc/blob/location_api_investigation/samples/location-api/kcp-location-api.md

**Comment by mikenairn** [comment]
Requires https://github.com/Kuadrant/kcp-glbc/issues/197

**Comment by mikenairn** [comment]
The location concept is best explained here https://github.com/kcp-dev/kcp/blob/main/docs/locations-and-scheduling.md#main-concepts.

Currently (KCP 0.5.0), only one workloadcluster in a location will be chosen as part of the scheduling/placement process, This means having a workload deployed to more than one workloadcluster via a location is not possible, **yet**.
However, it is possible to force it onto 2 workload clusters by manually adding the workload placement labels to the namespace:

```
        "labels": {
            "kubernetes.io/metadata.name": "default",  
            "state.internal.workload.kcp.dev/kcp-cluster-1": "Sync"                                          
            "state.internal.workload.kcp.dev/kcp-cluster-2": "Sync"
        }, 
```

This will deploy everything in that namespace to both clusters, but it should be noted that the status of resources in KCP just receive the status of the last updated resource on a pCluster i.e. The status block of an ingress will be from one or the other depending on what one synced last.

For our needs we must use the advanced scheduling feature in order to get back a status from all ingresses https://github.com/kcp-dev/kcp/pull/942

We will be adding the creation of locations to our local setup as part of the upgrade work to KCP 0.5.0 https://github.com/Kuadrant/kcp-glbc/issues/197
